### PR TITLE
fixed xml query and output

### PR DESCRIPTION
**Pull request by chreman**
hopefully addresses [#11](https://github.com/njahn82/ropenaire/issues/11)

### CODE REVIEW

**Comment by sckott** [comment]
@chreman you needed to update to most recent on `sckott:master` before pushing here :)

**Comment by sckott** [comment]
@chreman did you mean to close this?

**Comment by chreman** [comment]
yes, the PR was no longer relevant/correct with the merged updates, my latest 'insight' was https://github.com/njahn82/ropenaire/issues/11#issuecomment-372971290

**Comment by sckott** [comment]
ok

**Pull request closed without merging**
